[package]
name = "reddit-rs"
version = "0.1.0"
authors = ["Chathura Colombage <dcdewaka@gmail.com>"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1"
futures = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
